{% set name = "limix" %}
{% set version = "1.0.18" %}
{% set sha256 = "486f55baeeacb204965ed1baf01bf717bb43718240453b884035d526ac4b8bbb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win or linux32]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - cython >=0.28.4
    - numpy >=1.14.5
    - pytest-runner >=4.2
    - python
    - setuptools >=40.0.0
    - toolchain
  run:
    - asciitree >=0.3.3
    - dask[array,bag,dataframe,delayed] >=0.18.1
    - glimix-core >=1.5.2
    - h5py >=2.8.0
    - joblib >=0.12.0
    - limix-core >=1.0.2
    - limix-legacy >=0.8.12
    - matplotlib >=2.2.2
    - ncephes >=1.0.40
    - numpy-sugar >=1.2.5
    - numpy >=1.14.5
    - pandas-plink >=1.2.28
    - pandas >=0.23.3
    - python
    - scikit-learn >=0.19.1
    - scipy >=1.1.0
    - tqdm >=4.23.4
test:
  requires:
    - pytest >=3
  imports:
    - limix
  commands:
    - python -c "import sys; import limix; sys.exit(limix.test())"

about:
  home: https://github.com/limix/limix
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A flexible and fast mixed model toolbox'
  doc_url: https://limix.readthedocs.io
  dev_url: https://github.com/limix/limix

extra:
  recipe-maintainers:
    - Horta
