{% set name = "limix" %}
{% set version = "1.0.17" %}
{% set sha256 = "7426c89e4831575eb7cc09659135c1d8d57b6402d988063b140e02a94d6ffb8d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win or linux32]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - pytest-runner
    - cython
    - numpy
  run:
    - python
    - scikit-learn
    - pandas
    - scipy
    - h5py
    - matplotlib
    - numpy
    - glimix-core >=1.2.25,<1.3.0
    - limix-core
    - limix-legacy
    - scikit-learn
    - dask
    - pandas-plink
    - joblib
    - tqdm
    - asciitree
    - ncephes
    - numpy-sugar >=1.2.3

test:
  requires:
    - pytest >=3
  imports:
    - limix
  commands:
    - python -c "import sys; import limix; sys.exit(limix.test())"

about:
  home: https://github.com/limix/limix
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A flexible and fast mixed model toolbox'
  doc_url: https://limix.readthedocs.io
  dev_url: https://github.com/limix/limix

extra:
  recipe-maintainers:
    - Horta
