{% set name = "limix" %}
{% set version = "1.0.18" %}
{% set sha256 = "486f55baeeacb204965ed1baf01bf717bb43718240453b884035d526ac4b8bbb<Paste>" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win or linux32]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
    - cython
    - toolchain
    - numpy
  run:
    - python
    - ansicolors>=1.1.8
    - asciitree>=0.3.3
    - bgen-reader>=2.0.4
    - brent-search>=1.0.33
    - dask[distributed,array,dataframe]>=0.18.1
    - glimix-core>=1.5.2
    - h5py>=2.8.0
    - humanfriendly>=4.12.1
    - joblib>=0.12.0
    - limix-plot>=0.0.2
    - matplotlib>=2.2.2
    - nb2plots>=0.6
    - ndarray-listener>=1.1.2
    - numba>=0.38.1
    - numpy-sugar>=1.2.5
    - numpy>=1.14.5
    - pandas-plink>=1.2.28
    - pandas>=0.23.3
    - pypandoc>=1.4
    - pytest-doctestplus>=0.1.3
    - pytest>=3.6.3
    - scikit-learn>=0.19.1
    - scipy>=1.1.0
    - seaborn>=0.8.1
    - statsmodels>=0.9.0
    - tqdm>=4.23.4

test:
  requires:
    - pytest >=3
  imports:
    - limix
  commands:
    - python -c "import sys; import limix; sys.exit(limix.test())"

about:
  home: https://github.com/limix/limix
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A flexible and fast mixed model toolbox'
  doc_url: https://limix.readthedocs.io
  dev_url: https://github.com/limix/limix

extra:
  recipe-maintainers:
    - Horta
