{% set name = "limix" %}
{% set version = "1.0.10" %}
{% set sha256 = "b18a8210a32f54f72a780845985b046a795f57c1987f6be31b44043a59f286f7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win or linux32]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cython
    - toolchain
    - numpy x.x
  run:
    - python
    - scikit-learn
    - pandas
    - scipy >=0.19.1
    - h5py
    - matplotlib
    - numpy x.x
    - glimix-core >=1.2.19
    - limix-core >=1.0.1
    - limix-legacy >=0.8.12
    - scikit-learn
    - dask
    - pandas-plink >=1.2.1
    - joblib >=0.11
    - tqdm >=4.11.2
    - asciitree
    - ncephes >=1.0.40
    - numpy-sugar >=1.0.47

test:
  requires:
    - pytest >=3
  imports:
    - limix
  commands:
    - python -c "import sys; import limix; sys.exit(limix.test())"

about:
  home: https://github.com/limix/limix
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A flexible and fast mixed model toolbox'
  doc_url: https://limix.readthedocs.io
  dev_url: https://github.com/limix/limix

extra:
  recipe-maintainers:
    - Horta
