{% set name = "limix" %}
{% set version = "3.0.0" %}
{% set sha256 = "17be1695918bec0e76804092724aa529ac69027464b7449551b020df8d576784" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - numpy >=1.16.2
    - pip
    - pytest-runner
    - python >3
    - setuptools
  run:
    - appdirs >=1.4.3
    - asciitree >=0.3.3
    - bgen-reader >=3.0.5
    - blessings >=1.7
    - brent-search >=2.0.0
    - click >=7.0
    - colorama >=0.4.1
    - dask[array,dataframe] >=1.2.0
    - glimix-core >=3.1.5
    - h5py >=2.9.0
    - humanfriendly >=4.18
    - joblib >=0.13.2
    - limix-plot >=0.1.0
    - matplotlib >=3.0.3
    - monotonic >=1.5
    - ndarray-listener >=2.0.0
    - netcdf4 >=1.5.0.1
    - numba >=0.43.1
    - numpy >=1.16.2
    - numpy-sugar >=1.4.1
    - optimix >=3.0.3
    - pandas >=0.24.2
    - pandas-plink >=1.2.30
    - pytest >=4.4.1
    - pytest-doctestplus >=0.3.0
    - python >3
    - scikit-learn >=0.20.3
    - scipy >=1.2.1
    - seaborn >=0.9.0
    - setuptools >=41.0.0
    - sphinxcontrib-programoutput >=0.14
    - statsmodels >=0.9.0
    - struct-lmm >=0.2.4
    - tqdm >=4.31.1
    - xarray >=0.12.1

test:
  requires:
    - pytest >=3
  imports:
    - limix
  commands:
    - python -c "import sys; import limix; sys.exit(limix.test())"

about:
  home: https://github.com/limix/limix
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A flexible and fast mixed model toolbox'
  doc_url: https://limix.readthedocs.io
  dev_url: https://github.com/limix/limix

extra:
  recipe-maintainers:
    - Horta
