{% set name = "limix" %}
{% set version = "2.0.2" %}
{% set sha256 = "80828043550213f33703dbe095c3a3d9888ea2daffb707bcbfcb15537331828a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win or linux32]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv" 

requirements:
  host:
    - pip
    - python
    - setuptools
    - pytest-runner
  run:
    - ipython
    - pytest-doctestplus >=0.2.0
    - seaborn >=0.9.0
    - asciitree >=0.3.3
    - bgen-reader >=2.0.4
    - brent-search >=1.0.33
    - click>=7.0
    - dask[distributed,array,dataframe] >=0.18.1
    - glimix-core >=2.0.3
    - h5py >=2.8.0
    - humanfriendly >=4.16.1
    - joblib >=0.12.0
    - limix-plot >=0.0.11 # needs recipe
    - matplotlib >=2.2.3
    - ndarray-listener >=1.1.2
    - netcdf4 >= 1.4.0
    - numba >=0.39.0
    - numpy >=1.15.0
    - numpy-sugar >=1.2.8
    - pandas-plink >=1.2.28
    - pandas >=0.23.4
    - pytest >=3.7.0
    - pytest-doctestplus >=0.2.0
    - python
    - scikit-learn >=0.18.0
    - scipy >=1.1.0
    - statsmodels >=0.9.0
    - tqdm >=4.25.0
    - xarray >=0.10.9
    - monotonic >=1.5
    - limix-lmm >=0.1.2 # needs recipe
    - struct-lmm >=0.2.1 # needs recipe

test:
  requires:
    - pytest >=3
  imports:
    - limix
  commands:
    - python -c "import sys; import limix; sys.exit(limix.test())"

about:
  home: https://github.com/limix/limix
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A flexible and fast mixed model toolbox'
  doc_url: https://limix.readthedocs.io
  dev_url: https://github.com/limix/limix

extra:
  recipe-maintainers:
    - Horta
