{% set name = "limix" %}
{% set version = "0.8.6" %}
{% set sha256 = "e0ce91f22df6489cb01716d806f36e58723445d62c539a367d2b54126aa60db1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win or np==112]
  script: python setup.py install --compatible --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy x.x
  run:
    - python
    - scikit-learn
    - pandas
    - scipy
    - h5py
    - matplotlib
    - numpy x.x

test:
  requires:
    - pytest >=3
  imports:
    - limix
  commands:
    - python -c "import sys; import limix; sys.exit(limix.test())"

about:
  home: http://github.com/PMBio/limix
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A flexible and fast mixed model toolbox'
  doc_url: https://github.com/PMBio/limix
  dev_url: https://github.com/PMBio/limix

extra:
  recipe-maintainers:
    - Horta
