{% set name = "limix" %}
{% set version = "1.0.6" %}
{% set sha256 = "8af0ca44b3545bb807b7e39af95ef1275c68c4cdf2403bd4ce399572698473e1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win or linux32]
  script: python setup.py install --compatible --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cython
    - toolchain
    - numpy x.x
  run:
    - python
    - scikit-learn
    - pandas
    - scipy
    - h5py
    - matplotlib
    - numpy x.x
    - glimix-core
    - limix-core
    - limix-legacy
    - scikit-learn
    - dask
    - pandas-plink
    - joblib
    - tqdm
    - asciitree
    - ncephes
    - numpy-sugar

test:
  requires:
    - pytest >=3
  imports:
    - limix
  commands:
    - python -c "import sys; import limix; sys.exit(limix.test())"

about:
  home: https://github.com/limix/limix
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A flexible and fast mixed model toolbox'
  doc_url: https://limix.readthedocs.io
  dev_url: https://github.com/limix/limix

extra:
  recipe-maintainers:
    - Horta
