{% set name = "limix" %}
{% set version = "2.0.0" %}
{% set sha256 = "16af3c2d0aec9390f65e6a9710ba9a9dcab1d85c687f21ec4407b38999c38497" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win or linux32]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
    - cython
    - toolchain
    - numpy >=1.14.5
  run:
    - asciitree >=0.3.3
    - bgen-reader >=2.0.4
    - brent-search >=1.0.33
    - dask[distributed,array,dataframe] >=0.18.1
    - glimix-core >=1.5.2
    - h5py >=2.8.0
    - humanfriendly >=4.12.1
    - joblib >=0.12.0
    - limix-core >=1.0.2
    - limix-legacy >=0.8.12
    - matplotlib >=2.2.2
    - ndarray-listener >=1.1.2
    - numba >=0.38.1
    - numpy  >=1.14.5
    - numpy-sugar >=1.2.5
    - pandas >=0.23.3
    - pandas-plink >=1.2.28
    - pypandoc >=1.4
    - pytest
    - pytest-doctestplus >=0.1.3
    - python
    - scikit-learn >=0.19.1
    - scipy >=1.1.0
    - seaborn >=0.8.1
    - statsmodels >=0.9.0
    - tqdm >=4.23.4

test:
  requires:
    - pytest >=3
  imports:
    - limix
  commands:
    - python -c "import sys; import limix; sys.exit(limix.test())"

about:
  home: https://github.com/limix/limix
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A flexible and fast mixed model toolbox'
  doc_url: https://limix.readthedocs.io
  dev_url: https://github.com/limix/limix

extra:
  recipe-maintainers:
    - Horta
