travis:
  secure:
    BINSTAR_TOKEN: cElF1CA1x778w1TQ7tI6ZiYkJNbqlVUHFG1a7ToBArcXNAaWyhbaBE9P7vFkAkSkL96Gc4rWpLLGqRb2Srm6aKGuX5UnVyNR5FO2gnhh9ZDsh9MAcJ3oAcc34YwN5pOJpCjfq8t0qFSDMxccroKRLCqdeyD8scWqvwNN1ggrXQ+7iwORRgJzOpzMfoUXmrfC9xmZnKRDYsh4hBiR0sw2VMPUwkcvDDhUHrtlCIdIC+a0D4KhFtjMShBrF/RgOUjFv7O98voybsMOgIXm8Sca/tXk2tIOpUatyP4MDQMiuJMMaotbCiZ2a1KjRe9bJZ/9KNUylXfWRvzKxZFpuP1BKYhJn0UXWfIraiLN4mNkho947vUQOgFTAyQtt9oULRlnYlahfaUnINf7Z4xka2uGOP38ofpxXTfppkA0DHHsdXaEHTIsYSEvZXNpkeJ1bPm3cOMX+MVuJMC4nJQdMNvBunky4tJ6YYEQuv9kXhcLIOalvktLSiX6r0FEVKH9msYGly/47mwAlC/Zq/Utyp2Z39qlhG2O0DcVlknfCEuKfPMJ5JnyDpESzMu8zGKaSsBN9+v/MeRNj9g9l+G4p/C5OdPC89+iQMLrHVBZYm68RpKd696jTwVvwAqZgfN2pD9+2alxSEbpXyVdc4xbICEeCiW3b1Y58kGjVirY2IiNe2U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
